---
title: "About Me"
---


::::{.animate__animated .animate__slideInUp .animate__faster}
:::{.panel-tabset}

# Experience

**Postdoccotral Researcher** (March 2023 – Current) \
Chalmers University of Technology, Sweden \
*Together with AstraZeneca imrpoving their de novo agent 'Reinvent' by integrating human feedback and preference* 
Supervisor: Prof. Dr. Ola Engkvist  

**Visiting Researcher** (January 2022 - July 2022) \
AstraZeneca, Sweden \
*Built a transformer model that generates molecular representation better suited for the screening of potential ion channel modulators.* 
Supervisor: Dr Christian Tyrchan

**Ph.D. Student** (October 2019 - February 2023) \
University of Münster, Germany \
*Using Feed-forwards and Graph Neural Networks generate improvied molecular representations that improve the results of similarity searches.*
Supervisor: Prof. Dr. Oliver Koch

**Master Student** (September 2018 - June - 2019) \
Sanquin, Netherlands \
*Improve the boostering schedule for Tetanus Antibody Donors using Bayesian Modeling.*

# Education

**M.Sc. Methedology and Statistics** (2017-2019) \
Utrecht University, Netherlands

**B.Sc. Psychology** (2014-2017) \
University of Twente, Netherlands


# Skills

**Programming** | Python | R | basic Fortran | PyTorch

**Computer Graphics** | Blender | Inkscape

**Teaching** | Intro To Datascience, *Utrecht* | Intro to AI for Life Sciences, *Münster* 

**Languages** | German | English | Dutch

:::

:::{.panel-tabset}
# Publications

### 2023
---

Zhang, Y.; Menke, J\*.; He, J.; Nittinger, E.; Tyrchan, C.; Koch, O.; Zhao, H. Similarity-Based Pairing Improves Efficiency of Siamese Neural Networks for Regression Tasks and Uncertainty Quantification. *Journal of Cheminformatics* **2023**, 15(1). [https://doi.org/10.1186/s13321-023-00744-6](https://doi.org/10.1186/s13321-023-00744-6). \
*Corresponding Author

Menke, J.; Homberg, S.; Koch, O. Introduction to Artificial Intelligence and Deep Learning Using Interactive Electronic Programming Notebooks. *Archiv Der Pharmazie* **2023**, 356 (7). [https://doi.org/10.1002/ardp.202200628](https://doi.org/10.1002/ardp.202200628).

### 2021
---

Menke, J.; Massa, J.; Koch, O. Natural Product Scores and Fingerprints Extracted from Artificial Neural Networks. *Computational and Structural Biotechnology Journal* **2021**, 19, 4593–4602. [https://doi.org/10.1016/j.csbj.2021.07.032](https://doi.org/10.1016/j.csbj.2021.07.032).

Computational Ion Channel Research: From the Application of Artificial Intelligence to Molecular Dynamics Simulations. *Cellular Physiology and Biochemistry* **2020**, 55 (S3), 14–45. [https://doi.org/10.33594/000000336](https://doi.org/10.33594/000000336).

Menke, J.; Koch, O. Using Domain-Specific Fingerprints Generated through Neural Networks to Enhance Ligand-Based Virtual Screening. *Journal of Chemical Information and Modeling* **2021**, 61 (2), 664–675. [https://doi.org/10.1021/acs.jcim.0c01208](https://doi.org/10.1021/acs.jcim.0c01208).


### 2019
---

Mulder, J.; Williams, D. R.; Gu, X.; Tomarken, A.; Böing-Messing, F.; Olsson-Collentine, A.; Meijerink, M.; Menke, J.; van Aert, R.; Fox, J.-P.; Hoijtink, H.; Rosseel, Y.; Wagenmakers, E.-J.; van Lissa, C. BFpack: Flexible Bayes Factor Testing of Scientific Theories in R. *Journal of Statistical Software* **2021**, 100 (18). [https://doi.org/10.18637/jss.v100.i18](https://doi.org/10.18637/jss.v100.i18).

# Extracurricular
 
**Student Representative for Gradua**


# Prizes


:::
::::

<br></br>
<br></br>
